//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeisureToPDF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public address()
        {
            this.leisure = new HashSet<leisure>();
        }
    
        public int id { get; set; }
        public int number { get; set; }
        public string street { get; set; }
        public string zip_code { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<leisure> leisure { get; set; }
    }
}
